{% set version = "0.2.0" %}

package:
  name: pyim
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  skip: True # [py27]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - python
    - setuptools

    # Basic dependencies
    - pandas >=0.18.1
    - pyfaidx >=0.4.8.1
    - pysam >=0.9.1
    - toolz >=0.8.0
    - tqdm
    - intervaltree
    - cutadapt

    # R dependencies
    - r
    - r-cimpl
    - rpy2 >=2.8.2

  run:
    - python

    # Basic dependencies
    - pandas >=0.18.1
    - pyfaidx >=0.4.8.1
    - pysam >=0.9.1
    - toolz >=0.8.0
    - tqdm
    - intervaltree
    - cutadapt

    # R dependencies
    - r
    - r-cimpl
    - rpy2 >=2.8.2

    # External dependencies
    - bowtie2

test:
    imports:
      - pyim
    commands:
      - pyim-align --help > /dev/null
      - pyim-annotate --help > /dev/null
      - pyim-bed --help > /dev/null
      - pyim-cis --help > /dev/null
      - pyim-demultiplex --help > /dev/null
      - pyim-merge --help > /dev/null
      - pyim-split --help > /dev/null

about:
  home: http://www.github.com/jrderuiter/pyim
  license: MIT License
  summary: 'PyIM (Python Insertional Mutagenesis) is a python package for
    analyzing insertional mutagenesis data from targeted sequencing of
    transposon insertion sites. The package provides several command line
    tools for identifying insertions, calling common insertion sites (CISs)
    and annotating insertions/CISs directly from the command line. It
    also aims to provides the basic building blocks for implementing
    new pipelines, CIS callers, etc.'
